"""Add IRR storage columns to funds table

Revision ID: 0e0cbd0e843f
Revises: 762e1a853f03
Create Date: 2025-08-03 15:28:38.658981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0cbd0e843f'
down_revision: Union[str, Sequence[str], None] = '762e1a853f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('irr_gross', sa.Float(), nullable=True))
    op.add_column('funds', sa.Column('irr_after_tax', sa.Float(), nullable=True))
    op.add_column('funds', sa.Column('irr_real', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'irr_real')
    op.drop_column('funds', 'irr_after_tax')
    op.drop_column('funds', 'irr_gross')
    # ### end Alembic commands ###
