"""add_tax_statement_id_to_fund_events

Revision ID: a67a839417fb
Revises: 0a4750fa04b2
Create Date: 2025-07-20 14:21:48.165175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67a839417fb'
down_revision: Union[str, Sequence[str], None] = '0a4750fa04b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_events', sa.Column('tax_statement_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fund_events_tax_statement_id'), 'fund_events', ['tax_statement_id'], unique=False)
    op.create_foreign_key(None, 'fund_events', 'tax_statements', ['tax_statement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fund_events', type_='foreignkey')
    op.drop_index(op.f('ix_fund_events_tax_statement_id'), table_name='fund_events')
    op.drop_column('fund_events', 'tax_statement_id')
    # ### end Alembic commands ###
