"""add dividend_franked and dividend_unfranked to distribution_type enum

Revision ID: abb88ad11ad3
Revises: 4e212ad5fd5d
Create Date: 2025-07-25 10:09:57.045132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb88ad11ad3'
down_revision: Union[str, Sequence[str], None] = '4e212ad5fd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed ALTER COLUMN statements as SQLite doesn't support them
    # REAL and FLOAT are the same in SQLite, so no change is needed
    # Note: Removed foreign key constraint as SQLite doesn't support ALTER TABLE ADD CONSTRAINT
    # Note: Removed index creation as it already exists
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed foreign key constraint drop as SQLite doesn't support ALTER TABLE DROP CONSTRAINT
    # Note: Removed index drop as it already exists and we don't want to drop it
    # Note: Removed ALTER COLUMN statements as SQLite doesn't support them
    pass
    # ### end Alembic commands ###
