"""add dividend_franked and dividend_unfranked to distribution_type enum

Revision ID: abb88ad11ad3
Revises: 4e212ad5fd5d
Create Date: 2025-07-25 10:09:57.045132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb88ad11ad3'
down_revision: Union[str, Sequence[str], None] = '4e212ad5fd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_events', 'previous_nav_per_share',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('fund_events', 'nav_change_absolute',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('fund_events', 'nav_change_percentage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_fund_events_tax_statement_id'), 'fund_events', ['tax_statement_id'], unique=False)
    op.create_foreign_key(None, 'fund_events', 'tax_statements', ['tax_statement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fund_events', type_='foreignkey')
    op.drop_index(op.f('ix_fund_events_tax_statement_id'), table_name='fund_events')
    op.alter_column('fund_events', 'nav_change_percentage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('fund_events', 'nav_change_absolute',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('fund_events', 'previous_nav_per_share',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
