"""Add grouping fields to FundEvent model

Revision ID: d1ac42f5994a
Revises: add_has_withholding_tax
Create Date: 2025-08-10 22:02:06.211424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ac42f5994a'
down_revision: Union[str, Sequence[str], None] = 'add_has_withholding_tax'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_events', sa.Column('is_grouped', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('fund_events', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('fund_events', sa.Column('group_type', sa.Enum('INTEREST_WITHHOLDING', 'TAX_STATEMENT', name='grouptype'), nullable=True))
    op.add_column('fund_events', sa.Column('group_position', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fund_events_group_id'), 'fund_events', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_events_group_id'), table_name='fund_events')
    op.drop_column('fund_events', 'group_position')
    op.drop_column('fund_events', 'group_type')
    op.drop_column('fund_events', 'group_id')
    op.drop_column('fund_events', 'is_grouped')
    # ### end Alembic commands ###
