"""base schema (no total_cost_basis)

Revision ID: f223dde71466
Revises: 
Create Date: 2025-07-13 23:17:49.745756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f223dde71466'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tax_jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('investment_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('risk_free_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'rate_date', 'rate_type', name='uq_risk_free_rate')
    )
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_company_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fund_type', sa.String(length=100), nullable=True),
    sa.Column('tracking_type', sa.Enum('NAV_BASED', 'COST_BASED', name='fundtype'), nullable=False),
    sa.Column('commitment_amount', sa.Float(), nullable=True),
    sa.Column('current_equity_balance', sa.Float(), nullable=True),
    sa.Column('average_equity_balance', sa.Float(), nullable=True),
    sa.Column('expected_irr', sa.Float(), nullable=True),
    sa.Column('expected_duration_months', sa.Integer(), nullable=True),
    sa.Column('current_units', sa.Float(), nullable=True),
    sa.Column('current_unit_price', sa.Float(), nullable=True),
    sa.Column('current_nav_total', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('final_tax_statement_received', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investment_company_id'], ['investment_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CAPITAL_CALL', 'RETURN_OF_CAPITAL', 'DISTRIBUTION', 'TAX_PAYMENT', 'DAILY_RISK_FREE_INTEREST_CHARGE', 'FY_DEBT_COST', 'NAV_UPDATE', 'UNIT_PURCHASE', 'UNIT_SALE', 'MANAGEMENT_FEE', 'CARRIED_INTEREST', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('nav_per_share', sa.Float(), nullable=True),
    sa.Column('units_owned', sa.Float(), nullable=True),
    sa.Column('distribution_type', sa.Enum('INCOME', 'DIVIDEND', 'DIVIDEND_FRANKED', 'DIVIDEND_UNFRANKED', 'INTEREST', 'RENT', 'CAPITAL_GAIN', 'OTHER', name='distributiontype'), nullable=True),
    sa.Column('tax_payment_type', sa.Enum('NON_RESIDENT_INTEREST_WITHHOLDING', 'NON_RESIDENT_INTEREST_WITHHOLDING_DIFFERENCE', 'CAPITAL_GAINS_TAX', 'EOFY_INTEREST_TAX', 'DIVIDENDS_FRANKED_TAX', 'DIVIDENDS_UNFRANKED_TAX', 'OTHER', name='taxpaymenttype'), nullable=True),
    sa.Column('units_purchased', sa.Float(), nullable=True),
    sa.Column('units_sold', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('brokerage_fee', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('current_equity_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_events_event_date'), 'fund_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_fund_events_event_type'), 'fund_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_fund_events_fund_id'), 'fund_events', ['fund_id'], unique=False)
    op.create_table('tax_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.Column('tax_payment_date', sa.Date(), nullable=True),
    sa.Column('interest_income_amount', sa.Float(), nullable=True),
    sa.Column('interest_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('interest_tax_amount', sa.Float(), nullable=True),
    sa.Column('interest_received_in_cash', sa.Float(), nullable=True),
    sa.Column('interest_receivable_this_fy', sa.Float(), nullable=True),
    sa.Column('interest_receivable_prev_fy', sa.Float(), nullable=True),
    sa.Column('interest_non_resident_withholding_tax_from_statement', sa.Float(), nullable=True),
    sa.Column('interest_non_resident_withholding_tax_already_withheld', sa.Float(), nullable=True),
    sa.Column('dividend_franked_income_amount', sa.Float(), nullable=True),
    sa.Column('dividend_unfranked_income_amount', sa.Float(), nullable=True),
    sa.Column('dividend_franked_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('dividend_unfranked_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('dividend_franked_tax_amount', sa.Float(), nullable=True),
    sa.Column('dividend_unfranked_tax_amount', sa.Float(), nullable=True),
    sa.Column('dividend_franked_income_amount_from_tax_statement_flag', sa.Boolean(), nullable=True),
    sa.Column('dividend_unfranked_income_amount_from_tax_statement_flag', sa.Boolean(), nullable=True),
    sa.Column('capital_gain_income_amount', sa.Float(), nullable=True),
    sa.Column('capital_gain_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('capital_gain_tax_amount', sa.Float(), nullable=True),
    sa.Column('capital_gain_discount_amount', sa.Float(), nullable=True),
    sa.Column('capital_gain_income_amount_from_tax_statement_flag', sa.Boolean(), nullable=True),
    sa.Column('fy_debt_interest_deduction_sum_of_daily_interest', sa.Float(), nullable=True),
    sa.Column('fy_debt_interest_deduction_rate', sa.Float(), nullable=True),
    sa.Column('fy_debt_interest_deduction_total_deduction', sa.Float(), nullable=True),
    sa.Column('non_resident', sa.Boolean(), nullable=True),
    sa.Column('accountant', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'entity_id', 'financial_year', name='unique_tax_statement')
    )
    op.create_index(op.f('ix_tax_statements_entity_id'), 'tax_statements', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tax_statements_financial_year'), 'tax_statements', ['financial_year'], unique=False)
    op.create_index(op.f('ix_tax_statements_fund_id'), 'tax_statements', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_statements_fund_id'), table_name='tax_statements')
    op.drop_index(op.f('ix_tax_statements_financial_year'), table_name='tax_statements')
    op.drop_index(op.f('ix_tax_statements_entity_id'), table_name='tax_statements')
    op.drop_table('tax_statements')
    op.drop_index(op.f('ix_fund_events_fund_id'), table_name='fund_events')
    op.drop_index(op.f('ix_fund_events_event_type'), table_name='fund_events')
    op.drop_index(op.f('ix_fund_events_event_date'), table_name='fund_events')
    op.drop_table('fund_events')
    op.drop_table('funds')
    op.drop_table('risk_free_rates')
    op.drop_table('investment_companies')
    op.drop_table('entities')
    # ### end Alembic commands ###
