"""Add fx_rates table for currency exchange rates

Revision ID: 23ba7495a951
Revises: d93de0407550
Create Date: 2025-10-04 23:36:49.227860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ba7495a951'
down_revision: Union[str, Sequence[str], None] = 'd93de0407550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the fx_rates table using existing currency enum
    op.execute("""
        CREATE TABLE fx_rates (
            id SERIAL PRIMARY KEY,
            from_currency currency NOT NULL,
            to_currency currency NOT NULL,
            date DATE NOT NULL,
            fx_rate FLOAT NOT NULL,
            created_at TIMESTAMP,
            updated_at TIMESTAMP,
            CONSTRAINT uq_fx_rate UNIQUE (from_currency, to_currency, date)
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
