"""update_investment_company_schema_only

Revision ID: 46920183bf9d
Revises: f1653be3687d
Create Date: 2025-09-26 22:40:30.305419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46920183bf9d'
down_revision: Union[str, Sequence[str], None] = 'f1653be3687d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_tax_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=4), nullable=False),
    sa.Column('financial_year_start_date', sa.Date(), nullable=False),
    sa.Column('financial_year_end_date', sa.Date(), nullable=False),
    sa.Column('tax_payment_date', sa.Date(), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('interest_income_amount', sa.Float(), nullable=True),
    sa.Column('interest_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('interest_tax_amount', sa.Float(), nullable=True),
    sa.Column('interest_received_in_cash', sa.Float(), nullable=True),
    sa.Column('interest_receivable_this_fy', sa.Float(), nullable=True),
    sa.Column('interest_receivable_prev_fy', sa.Float(), nullable=True),
    sa.Column('interest_non_resident_withholding_tax_from_statement', sa.Float(), nullable=True),
    sa.Column('interest_non_resident_withholding_tax_already_withheld', sa.Float(), nullable=True),
    sa.Column('dividend_franked_income_amount', sa.Float(), nullable=True),
    sa.Column('dividend_unfranked_income_amount', sa.Float(), nullable=True),
    sa.Column('dividend_franked_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('dividend_unfranked_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('dividend_franked_tax_amount', sa.Float(), nullable=True),
    sa.Column('dividend_unfranked_tax_amount', sa.Float(), nullable=True),
    sa.Column('dividend_franked_income_amount_from_tax_statement_flag', sa.Boolean(), nullable=True),
    sa.Column('dividend_unfranked_income_amount_from_tax_statement_flag', sa.Boolean(), nullable=True),
    sa.Column('capital_gain_income_amount', sa.Float(), nullable=True),
    sa.Column('capital_gain_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('capital_gain_tax_amount', sa.Float(), nullable=True),
    sa.Column('capital_gain_discount_amount', sa.Float(), nullable=True),
    sa.Column('capital_gain_income_amount_from_tax_statement_flag', sa.Boolean(), nullable=True),
    sa.Column('eofy_debt_interest_deduction_sum_of_daily_interest', sa.Float(), nullable=True),
    sa.Column('eofy_debt_interest_deduction_rate', sa.Float(), nullable=True),
    sa.Column('eofy_debt_interest_deduction_total_deduction', sa.Float(), nullable=True),
    sa.Column('non_resident', sa.Boolean(), nullable=True),
    sa.Column('accountant', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'entity_id', 'financial_year', name='unique_tax_statement')
    )
    op.create_index('idx_tax_statements_entity_financial_year', 'fund_tax_statements', ['entity_id', 'financial_year'], unique=False)
    op.create_index('idx_tax_statements_fund_financial_year', 'fund_tax_statements', ['fund_id', 'financial_year'], unique=False)
    op.create_index(op.f('ix_fund_tax_statements_entity_id'), 'fund_tax_statements', ['entity_id'], unique=False)
    op.create_index(op.f('ix_fund_tax_statements_financial_year'), 'fund_tax_statements', ['financial_year'], unique=False)
    op.create_index(op.f('ix_fund_tax_statements_fund_id'), 'fund_tax_statements', ['fund_id'], unique=False)
    op.create_table('domain_fund_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CAPITAL_CALL', 'RETURN_OF_CAPITAL', 'DISTRIBUTION', 'UNIT_PURCHASE', 'UNIT_SALE', 'NAV_UPDATE', 'DAILY_RISK_FREE_INTEREST_CHARGE', 'EOFY_DEBT_COST', 'TAX_PAYMENT', name='eventtype'), nullable=False),
    sa.Column('event_operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='eventoperation'), nullable=False),
    sa.Column('fund_event_id', sa.Integer(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_event_id'], ['fund_events.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_fund_events_fund_event_id'), 'domain_fund_events', ['fund_event_id'], unique=False)
    op.create_index(op.f('ix_domain_fund_events_fund_id'), 'domain_fund_events', ['fund_id'], unique=False)
    op.drop_index(op.f('idx_domain_events_fund_id_event_type'), table_name='domain_events')
    op.drop_index(op.f('idx_domain_events_processed'), table_name='domain_events')
    op.drop_index(op.f('idx_domain_events_timestamp'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_event_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_fund_id'), table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_table('alembic_version')
    op.drop_index(op.f('idx_tax_statements_entity_financial_year'), table_name='tax_statements')
    op.drop_index(op.f('idx_tax_statements_fund_financial_year'), table_name='tax_statements')
    op.drop_index(op.f('ix_tax_statements_entity_id'), table_name='tax_statements')
    op.drop_index(op.f('ix_tax_statements_financial_year'), table_name='tax_statements')
    op.drop_index(op.f('ix_tax_statements_fund_id'), table_name='tax_statements')
    op.drop_table('tax_statements')
    op.alter_column('bank_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('bank_accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('banks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('banks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('entities', 'tax_jurisdiction',
               existing_type=postgresql.ENUM('AU', 'US', 'UK', 'CA', 'NZ', 'SG', 'HK', 'JP', 'DE', 'FR', name='country'),
               nullable=True,
               existing_server_default=sa.text("'AU'::country"))
    op.alter_column('entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('entities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('fund_event_cash_flows', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('fund_event_cash_flows', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'fund_event_cash_flows', 'bank_accounts', ['bank_account_id'], ['id'])
    op.add_column('fund_events', sa.Column('dc_current_equity_balance', sa.Float(), nullable=True))
    op.add_column('fund_events', sa.Column('dc_risk_free_rate', sa.Float(), nullable=True))
    op.alter_column('fund_events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CAPITAL_CALL', 'RETURN_OF_CAPITAL', 'DISTRIBUTION', 'UNIT_PURCHASE', 'UNIT_SALE', 'NAV_UPDATE', 'DAILY_RISK_FREE_INTEREST_CHARGE', 'EOFY_DEBT_COST', 'TAX_PAYMENT', name='eventtype'),
               existing_nullable=False)
    op.drop_constraint(op.f('fund_events_tax_statement_id_fkey'), 'fund_events', type_='foreignkey')
    op.create_foreign_key(None, 'fund_events', 'fund_tax_statements', ['tax_statement_id'], ['id'])
    op.add_column('funds', sa.Column('fund_investment_type', sa.Enum('PRIVATE_EQUITY', 'VENTURE_CAPITAL', 'PRIVATE_DEBT', 'REAL_ESTATE', 'INFRASTRUCTURE', 'OTHER', name='fundinvestmenttype'), nullable=False))
    op.add_column('funds', sa.Column('tax_jurisdiction', sa.Enum('AU', 'US', 'UK', 'CA', 'NZ', 'SG', 'HK', 'JP', 'DE', 'FR', 'CN', 'KR', name='country'), nullable=False))
    op.add_column('funds', sa.Column('tax_statement_financial_year_type', sa.Enum('CALENDAR_YEAR', 'HALF_YEAR', name='fundtaxstatementfinancialyeartype'), nullable=False))
    op.add_column('funds', sa.Column('pnl', sa.Float(), nullable=True))
    op.add_column('funds', sa.Column('realized_pnl', sa.Float(), nullable=True))
    op.add_column('funds', sa.Column('unrealized_pnl', sa.Float(), nullable=True))
    op.add_column('funds', sa.Column('realized_pnl_capital_gain', sa.Float(), nullable=True))
    op.add_column('funds', sa.Column('unrealized_pnl_capital_gain', sa.Float(), nullable=True))
    op.add_column('funds', sa.Column('realized_pnl_dividend', sa.Float(), nullable=True))
    op.add_column('funds', sa.Column('realized_pnl_interest', sa.Float(), nullable=True))
    op.add_column('funds', sa.Column('realized_pnl_distribution', sa.Float(), nullable=True))
    op.alter_column('funds', 'tracking_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('COST_BASED', 'NAV_BASED', name='fundtrackingtype'),
               existing_nullable=False)
    op.alter_column('funds', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('AUD', 'USD', 'EUR', 'GBP', 'CAD', 'NZD', 'SGD', 'HKD', 'JPY', 'CHF', 'CNY', 'KRW', name='currency'),
               nullable=False)
    op.alter_column('funds', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'SUSPENDED', 'REALIZED', 'COMPLETED', name='fundstatus'),
               existing_nullable=True)
    op.create_foreign_key(None, 'funds', 'entities', ['entity_id'], ['id'])
    op.drop_column('funds', 'fund_type')
    op.add_column('investment_companies', sa.Column('total_funds', sa.Integer(), nullable=True))
    op.add_column('investment_companies', sa.Column('total_funds_active', sa.Integer(), nullable=True))
    op.add_column('investment_companies', sa.Column('total_funds_completed', sa.Integer(), nullable=True))
    op.add_column('investment_companies', sa.Column('total_funds_realized', sa.Integer(), nullable=True))
    op.add_column('investment_companies', sa.Column('total_commitment_amount', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('current_equity_balance', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('average_equity_balance', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('completed_irr_gross', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('completed_irr_after_tax', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('completed_irr_real', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('pnl', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('realized_pnl', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('unrealized_pnl', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('realized_pnl_capital_gain', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('unrealized_pnl_capital_gain', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('realized_pnl_dividend', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('realized_pnl_interest', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('realized_pnl_distribution', sa.Float(), nullable=True))
    op.add_column('investment_companies', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('investment_companies', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('investment_companies', sa.Column('current_duration', sa.Integer(), nullable=True))
    op.alter_column('investment_companies', 'company_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('PRIVATE_EQUITY', 'VENTURE_CAPITAL', 'REAL_ESTATE', 'INFRASTRUCTURE', 'CREDIT', 'HEDGE_FUND', 'FAMILY_OFFICE', 'INVESTMENT_BANK', 'ASSET_MANAGEMENT', 'INVESTMENT_GROUP', 'OTHER', name='companytype'),
               existing_nullable=True)
    op.alter_column('investment_companies', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED', name='companystatus'),
               nullable=True)
    op.drop_constraint(op.f('investment_companies_name_key'), 'investment_companies', type_='unique')
    op.alter_column('risk_free_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('risk_free_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_free_rates', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('risk_free_rates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(op.f('investment_companies_name_key'), 'investment_companies', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('investment_companies', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED', name='companystatus'),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('investment_companies', 'company_type',
               existing_type=sa.Enum('PRIVATE_EQUITY', 'VENTURE_CAPITAL', 'REAL_ESTATE', 'INFRASTRUCTURE', 'CREDIT', 'HEDGE_FUND', 'FAMILY_OFFICE', 'INVESTMENT_BANK', 'ASSET_MANAGEMENT', 'INVESTMENT_GROUP', 'OTHER', name='companytype'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('investment_companies', 'current_duration')
    op.drop_column('investment_companies', 'end_date')
    op.drop_column('investment_companies', 'start_date')
    op.drop_column('investment_companies', 'realized_pnl_distribution')
    op.drop_column('investment_companies', 'realized_pnl_interest')
    op.drop_column('investment_companies', 'realized_pnl_dividend')
    op.drop_column('investment_companies', 'unrealized_pnl_capital_gain')
    op.drop_column('investment_companies', 'realized_pnl_capital_gain')
    op.drop_column('investment_companies', 'unrealized_pnl')
    op.drop_column('investment_companies', 'realized_pnl')
    op.drop_column('investment_companies', 'pnl')
    op.drop_column('investment_companies', 'completed_irr_real')
    op.drop_column('investment_companies', 'completed_irr_after_tax')
    op.drop_column('investment_companies', 'completed_irr_gross')
    op.drop_column('investment_companies', 'average_equity_balance')
    op.drop_column('investment_companies', 'current_equity_balance')
    op.drop_column('investment_companies', 'total_commitment_amount')
    op.drop_column('investment_companies', 'total_funds_realized')
    op.drop_column('investment_companies', 'total_funds_completed')
    op.drop_column('investment_companies', 'total_funds_active')
    op.drop_column('investment_companies', 'total_funds')
    op.add_column('funds', sa.Column('fund_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'funds', type_='foreignkey')
    op.alter_column('funds', 'status',
               existing_type=sa.Enum('ACTIVE', 'SUSPENDED', 'REALIZED', 'COMPLETED', name='fundstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('funds', 'currency',
               existing_type=sa.Enum('AUD', 'USD', 'EUR', 'GBP', 'CAD', 'NZD', 'SGD', 'HKD', 'JPY', 'CHF', 'CNY', 'KRW', name='currency'),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('funds', 'tracking_type',
               existing_type=sa.Enum('COST_BASED', 'NAV_BASED', name='fundtrackingtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('funds', 'realized_pnl_distribution')
    op.drop_column('funds', 'realized_pnl_interest')
    op.drop_column('funds', 'realized_pnl_dividend')
    op.drop_column('funds', 'unrealized_pnl_capital_gain')
    op.drop_column('funds', 'realized_pnl_capital_gain')
    op.drop_column('funds', 'unrealized_pnl')
    op.drop_column('funds', 'realized_pnl')
    op.drop_column('funds', 'pnl')
    op.drop_column('funds', 'tax_statement_financial_year_type')
    op.drop_column('funds', 'tax_jurisdiction')
    op.drop_column('funds', 'fund_investment_type')
    op.drop_constraint(None, 'fund_events', type_='foreignkey')
    op.create_foreign_key(op.f('fund_events_tax_statement_id_fkey'), 'fund_events', 'tax_statements', ['tax_statement_id'], ['id'])
    op.alter_column('fund_events', 'event_type',
               existing_type=sa.Enum('CAPITAL_CALL', 'RETURN_OF_CAPITAL', 'DISTRIBUTION', 'UNIT_PURCHASE', 'UNIT_SALE', 'NAV_UPDATE', 'DAILY_RISK_FREE_INTEREST_CHARGE', 'EOFY_DEBT_COST', 'TAX_PAYMENT', name='eventtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('fund_events', 'dc_risk_free_rate')
    op.drop_column('fund_events', 'dc_current_equity_balance')
    op.drop_constraint(None, 'fund_event_cash_flows', type_='foreignkey')
    op.drop_column('fund_event_cash_flows', 'updated_at')
    op.drop_column('fund_event_cash_flows', 'created_at')
    op.alter_column('entities', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('entities', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('entities', 'tax_jurisdiction',
               existing_type=postgresql.ENUM('AU', 'US', 'UK', 'CA', 'NZ', 'SG', 'HK', 'JP', 'DE', 'FR', name='country'),
               nullable=False,
               existing_server_default=sa.text("'AU'::country"))
    op.alter_column('banks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('banks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bank_accounts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bank_accounts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_table('tax_statements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('tax_payment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('interest_income_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interest_income_tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interest_tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interest_received_in_cash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interest_receivable_this_fy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interest_receivable_prev_fy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interest_non_resident_withholding_tax_from_statement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interest_non_resident_withholding_tax_already_withheld', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividend_franked_income_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividend_unfranked_income_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividend_franked_income_tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividend_unfranked_income_tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividend_franked_tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividend_unfranked_tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dividend_franked_income_amount_from_tax_statement_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dividend_unfranked_income_amount_from_tax_statement_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('capital_gain_income_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('capital_gain_income_tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('capital_gain_tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('capital_gain_discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('capital_gain_income_amount_from_tax_statement_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('eofy_debt_interest_deduction_sum_of_daily_interest', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eofy_debt_interest_deduction_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eofy_debt_interest_deduction_total_deduction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('non_resident', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('accountant', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statement_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name=op.f('tax_statements_fund_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tax_statements_pkey')),
    sa.UniqueConstraint('fund_id', 'entity_id', 'financial_year', name=op.f('unique_tax_statement'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tax_statements_fund_id'), 'tax_statements', ['fund_id'], unique=False)
    op.create_index(op.f('ix_tax_statements_financial_year'), 'tax_statements', ['financial_year'], unique=False)
    op.create_index(op.f('ix_tax_statements_entity_id'), 'tax_statements', ['entity_id'], unique=False)
    op.create_index(op.f('idx_tax_statements_fund_financial_year'), 'tax_statements', ['fund_id', 'financial_year'], unique=False)
    op.create_index(op.f('idx_tax_statements_entity_financial_year'), 'tax_statements', ['entity_id', 'financial_year'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('domain_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('processed', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name=op.f('domain_events_fund_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('domain_events_pkey'))
    )
    op.create_index(op.f('ix_domain_events_fund_id'), 'domain_events', ['fund_id'], unique=False)
    op.create_index(op.f('ix_domain_events_event_type'), 'domain_events', ['event_type'], unique=False)
    op.create_index(op.f('idx_domain_events_timestamp'), 'domain_events', ['timestamp'], unique=False)
    op.create_index(op.f('idx_domain_events_processed'), 'domain_events', ['processed'], unique=False)
    op.create_index(op.f('idx_domain_events_fund_id_event_type'), 'domain_events', ['fund_id', 'event_type'], unique=False)
    op.drop_index(op.f('ix_domain_fund_events_fund_id'), table_name='domain_fund_events')
    op.drop_index(op.f('ix_domain_fund_events_fund_event_id'), table_name='domain_fund_events')
    op.drop_table('domain_fund_events')
    op.drop_index(op.f('ix_fund_tax_statements_fund_id'), table_name='fund_tax_statements')
    op.drop_index(op.f('ix_fund_tax_statements_financial_year'), table_name='fund_tax_statements')
    op.drop_index(op.f('ix_fund_tax_statements_entity_id'), table_name='fund_tax_statements')
    op.drop_index('idx_tax_statements_fund_financial_year', table_name='fund_tax_statements')
    op.drop_index('idx_tax_statements_entity_financial_year', table_name='fund_tax_statements')
    op.drop_table('fund_tax_statements')
    # ### end Alembic commands ###
