"""create_fresh_tables_with_correct_names

Revision ID: 767f21b3f548
Revises: 46920183bf9d
Create Date: 2025-09-26 22:53:24.183534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767f21b3f548'
down_revision: Union[str, Sequence[str], None] = '46920183bf9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.Enum('AU', 'US', 'UK', 'CA', 'NZ', 'SG', 'HK', 'JP', 'DE', 'FR', 'CN', 'KR', name='country'), nullable=False),
    sa.Column('bank_type', sa.Enum('COMMERCIAL', 'INVESTMENT', 'CENTRAL', 'COOPERATIVE', 'DIGITAL', name='banktype'), nullable=True),
    sa.Column('swift_bic', sa.String(length=11), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CLOSED', name='bankstatus'), nullable=True),
    sa.Column('current_number_of_bank_accounts', sa.Integer(), nullable=True),
    sa.Column('current_balance_in_bank_accounts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'COMPANY', 'TRUST', 'FUND', 'OTHER', name='entitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tax_jurisdiction', sa.Enum('AU', 'US', 'UK', 'CA', 'NZ', 'SG', 'HK', 'JP', 'DE', 'FR', 'CN', 'KR', name='country'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('investment_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_type', sa.Enum('PRIVATE_EQUITY', 'VENTURE_CAPITAL', 'REAL_ESTATE', 'INFRASTRUCTURE', 'CREDIT', 'HEDGE_FUND', 'FAMILY_OFFICE', 'INVESTMENT_BANK', 'ASSET_MANAGEMENT', 'INVESTMENT_GROUP', 'OTHER', name='companytype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('total_funds', sa.Integer(), nullable=True),
    sa.Column('total_funds_active', sa.Integer(), nullable=True),
    sa.Column('total_funds_completed', sa.Integer(), nullable=True),
    sa.Column('total_funds_realized', sa.Integer(), nullable=True),
    sa.Column('total_commitment_amount', sa.Float(), nullable=True),
    sa.Column('current_equity_balance', sa.Float(), nullable=True),
    sa.Column('average_equity_balance', sa.Float(), nullable=True),
    sa.Column('completed_irr_gross', sa.Float(), nullable=True),
    sa.Column('completed_irr_after_tax', sa.Float(), nullable=True),
    sa.Column('completed_irr_real', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl_capital_gain', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl_capital_gain', sa.Float(), nullable=True),
    sa.Column('realized_pnl_dividend', sa.Float(), nullable=True),
    sa.Column('realized_pnl_interest', sa.Float(), nullable=True),
    sa.Column('realized_pnl_distribution', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED', name='companystatus'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_investment_companies_company_type', 'investment_companies', ['company_type'], unique=False)
    op.create_index('idx_investment_companies_name_status', 'investment_companies', ['name', 'status'], unique=False)
    op.create_index('idx_investment_companies_status', 'investment_companies', ['status'], unique=False)
    op.create_index('idx_investment_companies_type_status', 'investment_companies', ['company_type', 'status'], unique=False)
    op.create_table('risk_free_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('AUD', 'USD', 'EUR', 'GBP', 'CAD', 'NZD', 'SGD', 'HKD', 'JPY', 'CHF', 'CNY', 'KRW', name='currency'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('rate_type', sa.Enum('GOVERNMENT_BOND', 'LIBOR', 'SOFR', name='riskfreeratetype'), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'date', 'rate_type', name='uq_risk_free_rate')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.Enum('AUD', 'USD', 'EUR', 'GBP', 'CAD', 'NZD', 'SGD', 'HKD', 'JPY', 'CHF', 'CNY', 'KRW', name='currency'), nullable=False),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'INVESTMENT', 'BUSINESS', 'TRUST', 'JOINT', name='bankaccounttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CLOSED', 'SUSPENDED', 'OVERDRAFT', name='bankaccountstatus'), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_id', 'account_number', name='uq_bank_account_number_unique'),
    sa.UniqueConstraint('entity_id', 'bank_id', 'account_number', name='uq_bank_account_unique')
    )
    op.create_index(op.f('ix_bank_accounts_bank_id'), 'bank_accounts', ['bank_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_entity_id'), 'bank_accounts', ['entity_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('direct_number', sa.String(length=50), nullable=True),
    sa.Column('direct_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investment_company_id'], ['investment_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contacts_company_name', 'contacts', ['investment_company_id', 'name'], unique=False)
    op.create_index('idx_contacts_investment_company_id', 'contacts', ['investment_company_id'], unique=False)
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_company_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fund_investment_type', sa.Enum('PRIVATE_EQUITY', 'VENTURE_CAPITAL', 'PRIVATE_DEBT', 'REAL_ESTATE', 'INFRASTRUCTURE', 'OTHER', name='fundinvestmenttype'), nullable=False),
    sa.Column('tracking_type', sa.Enum('COST_BASED', 'NAV_BASED', name='fundtrackingtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.Enum('AUD', 'USD', 'EUR', 'GBP', 'CAD', 'NZD', 'SGD', 'HKD', 'JPY', 'CHF', 'CNY', 'KRW', name='currency'), nullable=False),
    sa.Column('tax_jurisdiction', sa.Enum('AU', 'US', 'UK', 'CA', 'NZ', 'SG', 'HK', 'JP', 'DE', 'FR', 'CN', 'KR', name='country'), nullable=False),
    sa.Column('tax_statement_financial_year_type', sa.Enum('CALENDAR_YEAR', 'HALF_YEAR', name='fundtaxstatementfinancialyeartype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expected_irr', sa.Float(), nullable=True),
    sa.Column('expected_duration_months', sa.Integer(), nullable=True),
    sa.Column('commitment_amount', sa.Float(), nullable=True),
    sa.Column('current_equity_balance', sa.Float(), nullable=True),
    sa.Column('average_equity_balance', sa.Float(), nullable=True),
    sa.Column('completed_irr_gross', sa.Float(), nullable=True),
    sa.Column('completed_irr_after_tax', sa.Float(), nullable=True),
    sa.Column('completed_irr_real', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl_capital_gain', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl_capital_gain', sa.Float(), nullable=True),
    sa.Column('realized_pnl_dividend', sa.Float(), nullable=True),
    sa.Column('realized_pnl_interest', sa.Float(), nullable=True),
    sa.Column('realized_pnl_distribution', sa.Float(), nullable=True),
    sa.Column('current_units', sa.Float(), nullable=True),
    sa.Column('current_unit_price', sa.Float(), nullable=True),
    sa.Column('current_nav_total', sa.Float(), nullable=True),
    sa.Column('total_cost_basis', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REALIZED', 'COMPLETED', name='fundstatus'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investment_company_id'], ['investment_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_funds_end_date', 'funds', ['end_date'], unique=False)
    op.create_index('idx_funds_entity_id', 'funds', ['entity_id'], unique=False)
    op.create_index('idx_funds_equity_status', 'funds', ['current_equity_balance', 'status'], unique=False)
    op.create_index('idx_funds_investment_company_id', 'funds', ['investment_company_id'], unique=False)
    op.create_index('idx_funds_start_date', 'funds', ['start_date'], unique=False)
    op.create_index('idx_funds_status_tracking_type', 'funds', ['status', 'tracking_type'], unique=False)
    op.create_table('fund_tax_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('financial_year', sa.String(length=4), nullable=False),
    sa.Column('financial_year_start_date', sa.Date(), nullable=False),
    sa.Column('financial_year_end_date', sa.Date(), nullable=False),
    sa.Column('tax_payment_date', sa.Date(), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('interest_income_amount', sa.Float(), nullable=True),
    sa.Column('interest_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('interest_tax_amount', sa.Float(), nullable=True),
    sa.Column('interest_received_in_cash', sa.Float(), nullable=True),
    sa.Column('interest_receivable_this_fy', sa.Float(), nullable=True),
    sa.Column('interest_receivable_prev_fy', sa.Float(), nullable=True),
    sa.Column('interest_non_resident_withholding_tax_from_statement', sa.Float(), nullable=True),
    sa.Column('interest_non_resident_withholding_tax_already_withheld', sa.Float(), nullable=True),
    sa.Column('dividend_franked_income_amount', sa.Float(), nullable=True),
    sa.Column('dividend_unfranked_income_amount', sa.Float(), nullable=True),
    sa.Column('dividend_franked_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('dividend_unfranked_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('dividend_franked_tax_amount', sa.Float(), nullable=True),
    sa.Column('dividend_unfranked_tax_amount', sa.Float(), nullable=True),
    sa.Column('dividend_franked_income_amount_from_tax_statement_flag', sa.Boolean(), nullable=True),
    sa.Column('dividend_unfranked_income_amount_from_tax_statement_flag', sa.Boolean(), nullable=True),
    sa.Column('capital_gain_income_amount', sa.Float(), nullable=True),
    sa.Column('capital_gain_income_tax_rate', sa.Float(), nullable=True),
    sa.Column('capital_gain_tax_amount', sa.Float(), nullable=True),
    sa.Column('capital_gain_discount_amount', sa.Float(), nullable=True),
    sa.Column('capital_gain_income_amount_from_tax_statement_flag', sa.Boolean(), nullable=True),
    sa.Column('eofy_debt_interest_deduction_sum_of_daily_interest', sa.Float(), nullable=True),
    sa.Column('eofy_debt_interest_deduction_rate', sa.Float(), nullable=True),
    sa.Column('eofy_debt_interest_deduction_total_deduction', sa.Float(), nullable=True),
    sa.Column('non_resident', sa.Boolean(), nullable=True),
    sa.Column('accountant', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'entity_id', 'financial_year', name='unique_tax_statement')
    )
    op.create_index('idx_tax_statements_entity_financial_year', 'fund_tax_statements', ['entity_id', 'financial_year'], unique=False)
    op.create_index('idx_tax_statements_fund_financial_year', 'fund_tax_statements', ['fund_id', 'financial_year'], unique=False)
    op.create_index(op.f('ix_fund_tax_statements_entity_id'), 'fund_tax_statements', ['entity_id'], unique=False)
    op.create_index(op.f('ix_fund_tax_statements_financial_year'), 'fund_tax_statements', ['financial_year'], unique=False)
    op.create_index(op.f('ix_fund_tax_statements_fund_id'), 'fund_tax_statements', ['fund_id'], unique=False)
    op.create_table('fund_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CAPITAL_CALL', 'RETURN_OF_CAPITAL', 'DISTRIBUTION', 'UNIT_PURCHASE', 'UNIT_SALE', 'NAV_UPDATE', 'DAILY_RISK_FREE_INTEREST_CHARGE', 'EOFY_DEBT_COST', 'TAX_PAYMENT', name='eventtype'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('nav_per_share', sa.Float(), nullable=True),
    sa.Column('previous_nav_per_share', sa.Float(), nullable=True),
    sa.Column('nav_change_absolute', sa.Float(), nullable=True),
    sa.Column('nav_change_percentage', sa.Float(), nullable=True),
    sa.Column('units_owned', sa.Float(), nullable=True),
    sa.Column('distribution_type', sa.Enum('INCOME', 'DIVIDEND_FRANKED', 'DIVIDEND_UNFRANKED', 'INTEREST', 'RENT', 'CAPITAL_GAIN', name='distributiontype'), nullable=True),
    sa.Column('tax_withholding', sa.Float(), nullable=True),
    sa.Column('has_withholding_tax', sa.Boolean(), nullable=True),
    sa.Column('tax_payment_type', sa.Enum('NON_RESIDENT_INTEREST_WITHHOLDING', 'NON_RESIDENT_INTEREST_WITHHOLDING_DIFFERENCE', 'CAPITAL_GAINS_TAX', 'EOFY_INTEREST_TAX', 'DIVIDENDS_FRANKED_TAX', 'DIVIDENDS_UNFRANKED_TAX', name='taxpaymenttype'), nullable=True),
    sa.Column('tax_statement_id', sa.Integer(), nullable=True),
    sa.Column('units_purchased', sa.Float(), nullable=True),
    sa.Column('units_sold', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('brokerage_fee', sa.Float(), nullable=True),
    sa.Column('current_equity_balance', sa.Float(), nullable=True),
    sa.Column('dc_current_equity_balance', sa.Float(), nullable=True),
    sa.Column('dc_risk_free_rate', sa.Float(), nullable=True),
    sa.Column('is_cash_flow_complete', sa.Boolean(), nullable=True),
    sa.Column('is_grouped', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('group_type', sa.Enum('INTEREST_WITHHOLDING', 'TAX_STATEMENT', name='grouptype'), nullable=True),
    sa.Column('group_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['tax_statement_id'], ['fund_tax_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fund_events_event_date', 'fund_events', ['event_date'], unique=False)
    op.create_index('idx_fund_events_event_type', 'fund_events', ['event_type'], unique=False)
    op.create_index('idx_fund_events_fund_date', 'fund_events', ['fund_id', 'event_date'], unique=False)
    op.create_index('idx_fund_events_fund_id', 'fund_events', ['fund_id'], unique=False)
    op.create_index('idx_fund_events_fund_id_event_date', 'fund_events', ['fund_id', 'event_date'], unique=False)
    op.create_index('idx_fund_events_fund_type', 'fund_events', ['fund_id', 'event_type'], unique=False)
    op.create_index('idx_fund_events_group_id', 'fund_events', ['group_id'], unique=False)
    op.create_index('idx_fund_events_tax_statement_id', 'fund_events', ['tax_statement_id'], unique=False)
    op.create_index('idx_fund_events_type_date', 'fund_events', ['event_type', 'event_date'], unique=False)
    op.create_index(op.f('ix_fund_events_event_date'), 'fund_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_fund_events_event_type'), 'fund_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_fund_events_fund_id'), 'fund_events', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_events_group_id'), 'fund_events', ['group_id'], unique=False)
    op.create_index(op.f('ix_fund_events_tax_statement_id'), 'fund_events', ['tax_statement_id'], unique=False)
    op.create_table('domain_fund_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CAPITAL_CALL', 'RETURN_OF_CAPITAL', 'DISTRIBUTION', 'UNIT_PURCHASE', 'UNIT_SALE', 'NAV_UPDATE', 'DAILY_RISK_FREE_INTEREST_CHARGE', 'EOFY_DEBT_COST', 'TAX_PAYMENT', name='eventtype'), nullable=False),
    sa.Column('event_operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='eventoperation'), nullable=False),
    sa.Column('fund_event_id', sa.Integer(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_event_id'], ['fund_events.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_fund_events_fund_event_id'), 'domain_fund_events', ['fund_event_id'], unique=False)
    op.create_index(op.f('ix_domain_fund_events_fund_id'), 'domain_fund_events', ['fund_id'], unique=False)
    op.create_table('fund_event_cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_event_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('INFLOW', 'OUTFLOW', name='cashflowdirection'), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['fund_event_id'], ['fund_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fund_event_cash_flows_bank_account_id', 'fund_event_cash_flows', ['bank_account_id'], unique=False)
    op.create_index('idx_fund_event_cash_flows_currency', 'fund_event_cash_flows', ['currency'], unique=False)
    op.create_index('idx_fund_event_cash_flows_fund_event_id', 'fund_event_cash_flows', ['fund_event_id'], unique=False)
    op.create_index('idx_fund_event_cash_flows_transfer_date', 'fund_event_cash_flows', ['transfer_date'], unique=False)
    op.create_index(op.f('ix_fund_event_cash_flows_bank_account_id'), 'fund_event_cash_flows', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_fund_event_cash_flows_fund_event_id'), 'fund_event_cash_flows', ['fund_event_id'], unique=False)
    op.create_index(op.f('ix_fund_event_cash_flows_transfer_date'), 'fund_event_cash_flows', ['transfer_date'], unique=False)
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_fund_event_cash_flows_transfer_date'), table_name='fund_event_cash_flows')
    op.drop_index(op.f('ix_fund_event_cash_flows_fund_event_id'), table_name='fund_event_cash_flows')
    op.drop_index(op.f('ix_fund_event_cash_flows_bank_account_id'), table_name='fund_event_cash_flows')
    op.drop_index('idx_fund_event_cash_flows_transfer_date', table_name='fund_event_cash_flows')
    op.drop_index('idx_fund_event_cash_flows_fund_event_id', table_name='fund_event_cash_flows')
    op.drop_index('idx_fund_event_cash_flows_currency', table_name='fund_event_cash_flows')
    op.drop_index('idx_fund_event_cash_flows_bank_account_id', table_name='fund_event_cash_flows')
    op.drop_table('fund_event_cash_flows')
    op.drop_index(op.f('ix_domain_fund_events_fund_id'), table_name='domain_fund_events')
    op.drop_index(op.f('ix_domain_fund_events_fund_event_id'), table_name='domain_fund_events')
    op.drop_table('domain_fund_events')
    op.drop_index(op.f('ix_fund_events_tax_statement_id'), table_name='fund_events')
    op.drop_index(op.f('ix_fund_events_group_id'), table_name='fund_events')
    op.drop_index(op.f('ix_fund_events_fund_id'), table_name='fund_events')
    op.drop_index(op.f('ix_fund_events_event_type'), table_name='fund_events')
    op.drop_index(op.f('ix_fund_events_event_date'), table_name='fund_events')
    op.drop_index('idx_fund_events_type_date', table_name='fund_events')
    op.drop_index('idx_fund_events_tax_statement_id', table_name='fund_events')
    op.drop_index('idx_fund_events_group_id', table_name='fund_events')
    op.drop_index('idx_fund_events_fund_type', table_name='fund_events')
    op.drop_index('idx_fund_events_fund_id_event_date', table_name='fund_events')
    op.drop_index('idx_fund_events_fund_id', table_name='fund_events')
    op.drop_index('idx_fund_events_fund_date', table_name='fund_events')
    op.drop_index('idx_fund_events_event_type', table_name='fund_events')
    op.drop_index('idx_fund_events_event_date', table_name='fund_events')
    op.drop_table('fund_events')
    op.drop_index(op.f('ix_fund_tax_statements_fund_id'), table_name='fund_tax_statements')
    op.drop_index(op.f('ix_fund_tax_statements_financial_year'), table_name='fund_tax_statements')
    op.drop_index(op.f('ix_fund_tax_statements_entity_id'), table_name='fund_tax_statements')
    op.drop_index('idx_tax_statements_fund_financial_year', table_name='fund_tax_statements')
    op.drop_index('idx_tax_statements_entity_financial_year', table_name='fund_tax_statements')
    op.drop_table('fund_tax_statements')
    op.drop_index('idx_funds_status_tracking_type', table_name='funds')
    op.drop_index('idx_funds_start_date', table_name='funds')
    op.drop_index('idx_funds_investment_company_id', table_name='funds')
    op.drop_index('idx_funds_equity_status', table_name='funds')
    op.drop_index('idx_funds_entity_id', table_name='funds')
    op.drop_index('idx_funds_end_date', table_name='funds')
    op.drop_table('funds')
    op.drop_index('idx_contacts_investment_company_id', table_name='contacts')
    op.drop_index('idx_contacts_company_name', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_bank_accounts_entity_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_bank_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_table('risk_free_rates')
    op.drop_index('idx_investment_companies_type_status', table_name='investment_companies')
    op.drop_index('idx_investment_companies_status', table_name='investment_companies')
    op.drop_index('idx_investment_companies_name_status', table_name='investment_companies')
    op.drop_index('idx_investment_companies_company_type', table_name='investment_companies')
    op.drop_table('investment_companies')
    op.drop_table('entities')
    op.drop_table('banks')
    # ### end Alembic commands ###
