"""refactor_domain_fund_events_to_domain_update_events

Revision ID: fe1b56aa9852
Revises: 23ba7495a951
Create Date: 2025-10-05 15:59:51.334204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe1b56aa9852'
down_revision: Union[str, Sequence[str], None] = '23ba7495a951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the new domainobjecttype enum using the project's established pattern
    domain_object_type_enum = sa.Enum('BANK', 'BANK_ACCOUNT', 'BANK_ACCOUNT_BALANCE', 'ENTITY', 'FUND', 'FUND_EVENT', 'FUND_EVENT_CASH_FLOW', 'FUND_TAX_STATEMENT', 'INVESTMENT_COMPANY', 'CONTACT', 'FX_RATE', 'RISK_FREE_RATE', name='domainobjecttype')
    domain_object_type_enum.create(op.get_bind())
    
    # Drop the old domain_fund_events table and its indexes
    op.drop_index('ix_domain_fund_events_fund_event_id', table_name='domain_fund_events')
    op.drop_index('ix_domain_fund_events_fund_id', table_name='domain_fund_events')
    op.drop_table('domain_fund_events')
    
    # Create the new domain_update_events table using raw SQL (following project pattern)
    op.execute("""
        CREATE TABLE domain_update_events (
            id SERIAL PRIMARY KEY,
            domain_object_type domainobjecttype NOT NULL,
            domain_object_id INTEGER NOT NULL,
            event_operation eventoperation NOT NULL,
            fund_event_type eventtype,
            event_data JSONB,
            timestamp TIMESTAMP WITH TIME ZONE NOT NULL
        )
    """)
    
    # Create indexes for the new table
    op.execute("CREATE INDEX idx_domain_update_events_domain_object_type ON domain_update_events (domain_object_type)")
    op.execute("CREATE INDEX idx_domain_update_events_domain_object_id ON domain_update_events (domain_object_id)")
    op.execute("CREATE INDEX idx_domain_update_events_timestamp ON domain_update_events (timestamp)")
    op.execute("CREATE INDEX idx_domain_update_events_event_operation ON domain_update_events (event_operation)")
    op.execute("CREATE INDEX idx_domain_update_events_fund_event_type ON domain_update_events (fund_event_type)")
    op.execute("CREATE INDEX idx_domain_update_events_object_type_id ON domain_update_events (domain_object_type, domain_object_id)")
    # Note: Other changes (bank_account_balances, fund_event_cash_flows) are handled by separate migrations
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fund_event_cash_flows', type_='foreignkey')
    op.drop_index(op.f('ix_fund_event_cash_flows_adjusted_bank_account_balance_id'), table_name='fund_event_cash_flows')
    op.drop_column('fund_event_cash_flows', 'adjusted_bank_account_balance_id')
    op.drop_column('fund_event_cash_flows', 'different_month')
    op.drop_column('fund_event_cash_flows', 'fund_event_date')
    op.create_table('domain_fund_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('CAPITAL_CALL', 'RETURN_OF_CAPITAL', 'DISTRIBUTION', 'UNIT_PURCHASE', 'UNIT_SALE', 'NAV_UPDATE', 'DAILY_RISK_FREE_INTEREST_CHARGE', 'EOFY_DEBT_COST', 'TAX_PAYMENT', name='eventtype'), autoincrement=False, nullable=False),
    sa.Column('event_operation', postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', name='eventoperation'), autoincrement=False, nullable=False),
    sa.Column('fund_event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fund_event_id'], ['fund_events.id'], name=op.f('domain_fund_events_fund_event_id_fkey')),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], name=op.f('domain_fund_events_fund_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('domain_fund_events_pkey'))
    )
    op.create_index(op.f('ix_domain_fund_events_fund_id'), 'domain_fund_events', ['fund_id'], unique=False)
    op.create_index(op.f('ix_domain_fund_events_fund_event_id'), 'domain_fund_events', ['fund_event_id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_bank_account_balances_bank_account_id'), table_name='bank_account_balances')
    op.drop_table('bank_account_balances')
    op.drop_table('domain_update_events')
    # ### end Alembic commands ###
