"""add current_nav_total to Fund

Revision ID: 932568d88bfa
Revises: 1a9fb49d4218
Create Date: 2025-07-13 22:58:05.618766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932568d88bfa'
down_revision: Union[str, Sequence[str], None] = '1a9fb49d4218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_statements_entity_id'), table_name='tax_statements')
    op.drop_index(op.f('ix_tax_statements_financial_year'), table_name='tax_statements')
    op.drop_index(op.f('ix_tax_statements_fund_id'), table_name='tax_statements')
    op.drop_table('tax_statements')
    op.drop_table('entities')
    op.drop_table('funds')
    op.drop_table('risk_free_rates')
    op.drop_table('investment_companies')
    op.drop_index(op.f('ix_fund_events_event_date'), table_name='fund_events')
    op.drop_index(op.f('ix_fund_events_event_type'), table_name='fund_events')
    op.drop_index(op.f('ix_fund_events_fund_id'), table_name='fund_events')
    op.drop_table('fund_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fund_id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=31), nullable=False),
    sa.Column('event_date', sa.DATE(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('nav_per_share', sa.FLOAT(), nullable=True),
    sa.Column('units_owned', sa.FLOAT(), nullable=True),
    sa.Column('distribution_type', sa.VARCHAR(length=12), nullable=True),
    sa.Column('tax_payment_type', sa.VARCHAR(length=44), nullable=True),
    sa.Column('units_purchased', sa.FLOAT(), nullable=True),
    sa.Column('units_sold', sa.FLOAT(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('brokerage_fee', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('current_equity_balance', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_events_fund_id'), 'fund_events', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_events_event_type'), 'fund_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_fund_events_event_date'), 'fund_events', ['event_date'], unique=False)
    op.create_table('investment_companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('risk_free_rates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('rate_date', sa.DATE(), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=False),
    sa.Column('rate_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'rate_date', 'rate_type', name=op.f('uq_risk_free_rate'))
    )
    op.create_table('funds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('investment_company_id', sa.INTEGER(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('fund_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tracking_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('commitment_amount', sa.FLOAT(), nullable=True),
    sa.Column('current_equity_balance', sa.FLOAT(), nullable=True),
    sa.Column('average_equity_balance', sa.FLOAT(), nullable=True),
    sa.Column('expected_irr', sa.FLOAT(), nullable=True),
    sa.Column('expected_duration_months', sa.INTEGER(), nullable=True),
    sa.Column('current_units', sa.FLOAT(), nullable=True),
    sa.Column('current_unit_price', sa.FLOAT(), nullable=True),
    sa.Column('total_cost_basis', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('final_tax_statement_received', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['investment_company_id'], ['investment_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('tax_jurisdiction', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tax_statements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fund_id', sa.INTEGER(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('financial_year', sa.VARCHAR(length=10), nullable=False),
    sa.Column('interest_tax_amount', sa.FLOAT(), nullable=True),
    sa.Column('tax_payment_date', sa.DATE(), nullable=True),
    sa.Column('fy_debt_interest_deduction_sum_of_daily_interest', sa.FLOAT(), nullable=True),
    sa.Column('fy_debt_interest_deduction_rate', sa.FLOAT(), nullable=True),
    sa.Column('fy_debt_interest_deduction_total_deduction', sa.FLOAT(), nullable=True),
    sa.Column('non_resident', sa.BOOLEAN(), nullable=True),
    sa.Column('accountant', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('statement_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('interest_receivable_this_fy', sa.FLOAT(), nullable=True),
    sa.Column('interest_receivable_prev_fy', sa.FLOAT(), nullable=True),
    sa.Column('interest_received_in_cash', sa.FLOAT(), nullable=True),
    sa.Column('interest_non_resident_withholding_tax_from_statement', sa.FLOAT(), nullable=True),
    sa.Column('interest_income_tax_rate', sa.FLOAT(), nullable=True),
    sa.Column('interest_income_amount', sa.FLOAT(), nullable=True),
    sa.Column('interest_non_resident_withholding_tax_already_withheld', sa.FLOAT(), nullable=True),
    sa.Column('dividend_franked_income_amount', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('dividend_unfranked_income_amount', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('dividend_franked_income_tax_rate', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('dividend_unfranked_income_tax_rate', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('franked_dividend_calculated_from_distributions', sa.FLOAT(), nullable=True),
    sa.Column('franked_dividend_manual_flag', sa.BOOLEAN(), nullable=True),
    sa.Column('unfranked_dividend_calculated_from_distributions', sa.FLOAT(), nullable=True),
    sa.Column('unfranked_dividend_manual_flag', sa.BOOLEAN(), nullable=True),
    sa.Column('dividend_franked_income_amount_from_tax_statement_flag', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=True),
    sa.Column('dividend_unfranked_income_amount_from_tax_statement_flag', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=True),
    sa.Column('dividend_franked_tax_amount', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('dividend_unfranked_tax_amount', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('capital_gain_income_amount', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('capital_gain_income_tax_rate', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('capital_gain_tax_amount', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('capital_gain_discount_amount', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=True),
    sa.Column('capital_gain_income_amount_from_tax_statement_flag', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'entity_id', 'financial_year', name=op.f('unique_tax_statement'))
    )
    op.create_index(op.f('ix_tax_statements_fund_id'), 'tax_statements', ['fund_id'], unique=False)
    op.create_index(op.f('ix_tax_statements_financial_year'), 'tax_statements', ['financial_year'], unique=False)
    op.create_index(op.f('ix_tax_statements_entity_id'), 'tax_statements', ['entity_id'], unique=False)
    # ### end Alembic commands ###
